name: lor_builder
description: LoR project.

version: 1.0.3+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: ^1.1.0
  equatable: ^0.6.1
  provider: ^3.1.0+1
  sembast: ^2.1.0
  path_provider: ^1.4.0
  shared_preferences: ^0.5.3+5
  cupertino_icons: ^0.1.2

  lor_deck_coder:
    path: ../lor_deck_coder/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.4
  
flutter_native_splash:
  color: "171e28"
flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "icon/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/lang/
   - assets/data/
   - assets/img/regions/
   - assets/img/champions/
   - assets/img/cards/
   - assets/img/types/
   - assets/img/rarities/
   - assets/img/keywords/
   - icon/

  fonts:
    - family: Alegreya
      fonts:
        - asset: fonts/AlegreyaSansSC-Regular.ttf
