name: lor_builder
description: LoR project.
publish_to: 'none'
version: 2.4.0+55

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: 3.1.1
  cupertino_icons: 1.0.5
  equatable: 2.0.5
  file: 6.1.4
  path_provider: 2.0.14
  percent_indicator: 4.2.3
  provider: 6.0.5
  sembast: 3.4.4
  shared_preferences: 2.1.0

  lor_deck_coder:
    path: ../lor_deck_coder/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: 2.2.19
  flutter_launcher_icons: 0.13.1
  
flutter_native_splash:
  color: "171e28"
flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "icon/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/lang/
   - assets/data/
   - assets/img/regions/
   - assets/img/champions/
   - assets/img/cards/
   - assets/img/types/
   - assets/img/rarities/
   - assets/img/keywords/
   - icon/

  fonts:
    - family: Alegreya
      fonts:
        - asset: fonts/AlegreyaSansSC-Regular.ttf
