name: lor_builder
description: LoR project.
publish_to: 'none'
version: 1.9.0+31

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  badges: 1.2.0
  cupertino_icons: 1.0.0
  equatable: 1.2.6
  path_provider: 1.6.28
  percent_indicator: 2.1.9+1
  provider: 4.3.3
  sembast: 2.4.10+4
  shared_preferences: 0.5.12+4

  lor_deck_coder:
    path: ../lor_deck_coder/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: 0.3.2
  flutter_launcher_icons: 0.8.1
  
flutter_native_splash:
  color: "171e28"
flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "icon/icon.png"

flutter:
  uses-material-design: true

  assets:
   - assets/lang/
   - assets/data/
   - assets/img/regions/
   - assets/img/champions/
   - assets/img/cards/
   - assets/img/types/
   - assets/img/rarities/
   - assets/img/keywords/
   - icon/

  fonts:
    - family: Alegreya
      fonts:
        - asset: fonts/AlegreyaSansSC-Regular.ttf
